<?php
	require_once('db_connect.php');
	require_once('query.php');
	session_create();
	if(session_check()==true)
	{
		if($_SESSION['LoggedINUser']==1)
		{
			include("dashboard_view.php");				
		}
		else
		{
			header("location:logout.php");
		}
	}
	else
	{
		header("location:index.php");
	}
?>